import Head from 'next/head'
import { Auth } from '../components/index/auth/Auth'
import { DashBoard } from '../components/index/home/DashBoard'
import { useContext } from 'react'
import { AuthContext } from '../state/AuthContext'

export default function Home() {
  const { user } = useContext(AuthContext)

  return (
    <div className="transform animate-fade-in-down">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{user ? <DashBoard /> : <Auth />}</div>
    </div>
  )
}
